name: NicholasLeo
description: 个人博客
meta_description: "NicholasLeo个人博客"

markdown: kramdown
highlighter: rouge
logo: false
baseurl: ''
domain_name: 'https://nicholasleo.github.io/'
google_analytics: 'UA-65961333-1'
disqus_username: NicholasLeo
plugins: [jekyll-paginate]

# details for the RSS feed generator
url:           'https://nicholasleo.github.io/'
author:        'NicholasLeo'

# pagination
paginate:      10

# outputting
permalink:     /:year/:month/:day/:title.html
timezone:      Asia/Kolkata


# custom collection
collections:
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - .gitlab-ci.yml
  - .codeclimate.yml
  - LICENSE.txt
  - README.md

# local serving
detach:  false
port:    4002
host:    0.0.0.0
